In [6]:
pip install pandas

Note: you may need to restart the kernel to use updated packages.


In [10]:
import pandas as pd
import os
import numpy as np
from scipy.stats import entropy

#  путь к каталогу, содержащему файлы CSV
directory_path = r'f:\Dell\Data_Science\HW_DS_5\data\idle'

#  пустой список, в который будут добавлены все DataFrame
all_dataframes = []

# список файлов в указанном каталоге
file_list = os.listdir(directory_path)

# чтение  каждого файла и сохранение его в DataFrame
for file_name in file_list:
    if file_name.endswith(".csv"):  
        file_path = os.path.join(directory_path, file_name)
        df = pd.read_csv(file_path)
        
        #  максимальные и минимальные значения для каждой оси движения
        max_x = df['accelerometer_X'].max()
        min_x = df['accelerometer_X'].min()
        max_y = df['accelerometer_Y'].max()
        min_y = df['accelerometer_Y'].min()
        max_z = df['accelerometer_Z'].max()
        min_z = df['accelerometer_Z'].min()
        
        # интерквартильный диапазон для столбца "accelerometer_X"
        iqr_x = df['accelerometer_X'].quantile(0.75) - df['accelerometer_X'].quantile(0.25)
        
        # Дополнительные метрики для столбца "accelerometer_Y"
        mean_y = df['accelerometer_Y'].mean()
        variance_y = df['accelerometer_Y'].var()
        std_dev_y = df['accelerometer_Y'].std()
        median_y = df['accelerometer_Y'].median()
        rms_y = np.sqrt(np.mean(df['accelerometer_Y'] ** 2))
        
        # Дополнительные метрики для столбца "accelerometer_Z"
        skewness_z = df['accelerometer_Z'].skew()
        kurtosis_z = df['accelerometer_Z'].kurt()
        iqr_z = df['accelerometer_Z'].quantile(0.75) - df['accelerometer_Z'].quantile(0.25)
        
        #  энтропию для каждой оси движения
        entropy_x = entropy(df['accelerometer_X'])
        entropy_y = entropy(df['accelerometer_Y'])
        entropy_z = entropy(df['accelerometer_Z'])
        
        # кросс-корреляцию бинарных комбинаций x, y и z
        cross_correlation_xy = np.correlate(df['accelerometer_X'], df['accelerometer_Y'], mode='same')
        cross_correlation_xz = np.correlate(df['accelerometer_X'], df['accelerometer_Z'], mode='same')
        cross_correlation_yz = np.correlate(df['accelerometer_Y'], df['accelerometer_Z'], mode='same')
        
        # все вычисленные метрики в датафрейм
        df['maximum_value_x'] = max_x
        df['minimum_value_x'] = min_x
        df['maximum_value_y'] = max_y
        df['minimum_value_y'] = min_y
        df['maximum_value_z'] = max_z
        df['minimum_value_z'] = min_z
        df['interquartile_range_x'] = iqr_x
        df['mean_y'] = mean_y
        df['variance_y'] = variance_y
        df['std_dev_y'] = std_dev_y
        df['median_y'] = median_y
        df['rms_y'] = rms_y
        df['entropy_x'] = entropy_x
        df['entropy_y'] = entropy_y
        df['entropy_z'] = entropy_z
        df['skewness_z'] = skewness_z
        df['kurtosis_z'] = kurtosis_z
        df['iqr_z'] = iqr_z
        df['cross_correlation_xy'] = cross_correlation_xy
        df['cross_correlation_xz'] = cross_correlation_xz
        df['cross_correlation_yz'] = cross_correlation_yz
        df ["id"] = 'idle'
        all_dataframes.append(df)
        
# объединение в один  DataFrame:
df_idle = pd.concat(all_dataframes, ignore_index=True)
df_idle = df_idle.iloc[:2000]
df_idle

accelerometer_X  accelerometer_Y  accelerometer_Z  maximum_value_x  \
0            1.000776         4.616021         8.576031         5.099650   
1            0.718261         4.209007         8.446744         5.099650   
2           -0.909797        -0.282516         9.203311         5.099650   
3            5.099650         0.148441         8.418014         5.099650   
4            1.762132        -0.162806         9.251195         5.099650   
...               ...              ...              ...              ...   
1995         0.110133         4.764462         8.489840         2.035071   
1996         0.603339         5.343858         8.145074         2.035071   
1997         1.077391         6.019023         7.422025         2.035071   
1998         0.799663         6.378154         7.402872         2.035071   
1999         0.790087         6.378154         7.230490         2.035071   

      minimum_value_x  maximum_value_y  minimum_value_y  maximum_value_z  \
0           -0.909797         4.616021        -0.282516         9.806650   
1           -0.909797         4.616021        -0.282516         9.806650   
2           -0.909797         4.616021        -0.282516         9.806650   
3           -0.909797         4.616021        -0.282516         9.806650   
4           -0.909797         4.616021        -0.282516         9.806650   
...               ...              ...              ...              ...   
1995        -2.896984         7.580043        -1.532289        10.065224   
1996        -2.896984         7.580043        -1.532289        10.065224   
1997        -2.896984         7.580043        -1.532289        10.065224   
1998        -2.896984         7.580043        -1.532289        10.065224   
1999        -2.896984         7.580043        -1.532289        10.065224   

      minimum_value_z  interquartile_range_x  ...  entropy_x  entropy_y  \
0            8.418014               0.065840  ...       -inf       -inf   
1            8.418014               0.065840  ...       -inf       -inf   
2            8.418014               0.065840  ...       -inf       -inf   
3            8.418014               0.065840  ...       -inf       -inf   
4            8.418014               0.065840  ...       -inf       -inf   
...               ...                    ...  ...        ...        ...   
1995         2.466028               0.934936  ...       -inf       -inf   
1996         2.466028               0.934936  ...       -inf       -inf   
1997         2.466028               0.934936  ...       -inf       -inf   
1998         2.466028               0.934936  ...       -inf       -inf   
1999         2.466028               0.934936  ...       -inf       -inf   

      entropy_z  skewness_z  kurtosis_z     iqr_z  cross_correlation_xy  \
0      3.400301   -2.365312    4.369874  0.034716             -0.817845   
1      3.400301   -2.365312    4.369874  0.034716             -0.679793   
2      3.400301   -2.365312    4.369874  0.034716             -0.889869   
3      3.400301   -2.365312    4.369874  0.034716             -0.774927   
4      3.400301   -2.365312    4.369874  0.034716             -0.756009   
...         ...         ...         ...       ...                   ...   
1995   3.370217   -1.385140    2.143166  2.284069             83.321567   
1996   3.370217   -1.385140    2.143166  2.284069             64.697363   
1997   3.370217   -1.385140    2.143166  2.284069             64.360059   
1998   3.370217   -1.385140    2.143166  2.284069             57.096742   
1999   3.370217   -1.385140    2.143166  2.284069             58.438785   

      cross_correlation_xz  cross_correlation_yz    id  
0                65.278404             69.562411  idle  
1                64.322335             68.427268  idle  
2                62.989091             67.019064  idle  
3                61.532475             65.808561  idle  
4                60.632498             64.651785  idle  
...                    ...          

In [9]:
import pandas as pd
import os
import numpy as np
from scipy.stats import entropy

#  путь к каталогу, содержащему файлы CSV
directory_path = r'f:\Dell\Data_Science\HW_DS_5\data\running'

#  пустой список, в который будут добавлены все DataFrame
all_dataframes = []

# список файлов в указанном каталоге
file_list = os.listdir(directory_path)

# чтение  каждого файла и сохранение его в DataFrame
for file_name in file_list:
    if file_name.endswith(".csv"):  
        file_path = os.path.join(directory_path, file_name)
        df = pd.read_csv(file_path)
        
        #  максимальные и минимальные значения для каждой оси движения
        max_x = df['accelerometer_X'].max()
        min_x = df['accelerometer_X'].min()
        max_y = df['accelerometer_Y'].max()
        min_y = df['accelerometer_Y'].min()
        max_z = df['accelerometer_Z'].max()
        min_z = df['accelerometer_Z'].min()
        
        # интерквартильный диапазон для столбца "accelerometer_X"
        iqr_x = df['accelerometer_X'].quantile(0.75) - df['accelerometer_X'].quantile(0.25)
        
        # Дополнительные метрики для столбца "accelerometer_Y"
        mean_y = df['accelerometer_Y'].mean()
        variance_y = df['accelerometer_Y'].var()
        std_dev_y = df['accelerometer_Y'].std()
        median_y = df['accelerometer_Y'].median()
        rms_y = np.sqrt(np.mean(df['accelerometer_Y'] ** 2))
        
        # Дополнительные метрики для столбца "accelerometer_Z"
        skewness_z = df['accelerometer_Z'].skew()
        kurtosis_z = df['accelerometer_Z'].kurt()
        iqr_z = df['accelerometer_Z'].quantile(0.75) - df['accelerometer_Z'].quantile(0.25)
        
        #  энтропию для каждой оси движения
        entropy_x = entropy(df['accelerometer_X'])
        entropy_y = entropy(df['accelerometer_Y'])
        entropy_z = entropy(df['accelerometer_Z'])
        
        # кросс-корреляцию бинарных комбинаций x, y и z
        cross_correlation_xy = np.correlate(df['accelerometer_X'], df['accelerometer_Y'], mode='same')
        cross_correlation_xz = np.correlate(df['accelerometer_X'], df['accelerometer_Z'], mode='same')
        cross_correlation_yz = np.correlate(df['accelerometer_Y'], df['accelerometer_Z'], mode='same')
        
        # все вычисленные метрики в датафрейм
        df['maximum_value_x'] = max_x
        df['minimum_value_x'] = min_x
        df['maximum_value_y'] = max_y
        df['minimum_value_y'] = min_y
        df['maximum_value_z'] = max_z
        df['minimum_value_z'] = min_z
        df['interquartile_range_x'] = iqr_x
        df['mean_y'] = mean_y
        df['variance_y'] = variance_y
        df['std_dev_y'] = std_dev_y
        df['median_y'] = median_y
        df['rms_y'] = rms_y
        df['entropy_x'] = entropy_x
        df['entropy_y'] = entropy_y
        df['entropy_z'] = entropy_z
        df['skewness_z'] = skewness_z
        df['kurtosis_z'] = kurtosis_z
        df['iqr_z'] = iqr_z
        df['cross_correlation_xy'] = cross_correlation_xy
        df['cross_correlation_xz'] = cross_correlation_xz
        df['cross_correlation_yz'] = cross_correlation_yz
        df ["id"] = 'running'
        all_dataframes.append(df)
        
# объединение в один  DataFrame:
df_running = pd.concat(all_dataframes, ignore_index=True)
df_running = df_running.iloc[:2000]
df_running

accelerometer_X  accelerometer_Y  accelerometer_Z  maximum_value_x  \
0           -4.151545         1.781286         2.173935        22.720974   
1            2.020706         3.706224         9.921572        22.720974   
2            1.762132         4.242526         8.078037        22.720974   
3           -0.445322        11.080365         6.756438        22.720974   
4            5.573702        13.436260        15.054740        22.720974   
...               ...              ...              ...              ...   
1995       -11.927913         1.082179         2.968810        26.575640   
1996         6.488287         6.105214        -6.272808        26.575640   
1997        18.832790        16.017210       -11.018116        26.575640   
1998        -8.169016        -1.532289         2.614468        26.575640   
1999        26.575640        32.570720         4.936844        26.575640   

      minimum_value_x  maximum_value_y  minimum_value_y  maximum_value_z  \
0           -4.941632        19.091364       -16.778566        25.775976   
1           -4.941632        19.091364       -16.778566        25.775976   
2           -4.941632        19.091364       -16.778566        25.775976   
3           -4.941632        19.091364       -16.778566        25.775976   
4           -4.941632        19.091364       -16.778566        25.775976   
...               ...              ...              ...              ...   
1995       -11.927913        33.154903       -16.548721        21.878216   
1996       -11.927913        33.154903       -16.548721        21.878216   
1997       -11.927913        33.154903       -16.548721        21.878216   
1998       -11.927913        33.154903       -16.548721        21.878216   
1999       -11.927913        33.154903       -16.548721        21.878216   

      minimum_value_z  interquartile_range_x  ...  entropy_x  entropy_y  \
0           -4.199430               6.890514  ...       -inf       -inf   
1           -4.199430               6.890514  ...       -inf       -inf   
2           -4.199430               6.890514  ...       -inf       -inf   
3           -4.199430               6.890514  ...       -inf       -inf   
4           -4.199430               6.890514  ...       -inf       -inf   
...               ...                    ...  ...        ...        ...   
1995       -16.510414               9.769541  ...       -inf       -inf   
1996       -16.510414               9.769541  ...       -inf       -inf   
1997       -16.510414               9.769541  ...       -inf       -inf   
1998       -16.510414               9.769541  ...       -inf       -inf   
1999       -16.510414               9.769541  ...       -inf       -inf   

      entropy_z  skewness_z  kurtosis_z     iqr_z  cross_correlation_xy  \
0          -inf    0.860710    1.222630  7.073669             97.614832   
1          -inf    0.860710    1.222630  7.073669            487.065297   
2          -inf    0.860710    1.222630  7.073669            918.034157   
3          -inf    0.860710    1.222630  7.073669             -6.056965   
4          -inf    0.860710    1.222630  7.073669            296.038840   
...         ...         ...         ...       ...                   ...   
1995       -inf    0.477087    1.600641  7.084442           1993.931382   
1996       -inf    0.477087    1.600641  7.084442           -217.150658   
1997       -inf    0.477087    1.600641  7.084442           1383.389515   
1998       -inf    0.477087    1.600641  7.084442            220.262764   
1999       -inf    0.477087    1.600641  7.084442           1119.984666   

      cross_correlation_xz  cross_correlation_yz       id  
0               212.352160            135.731603  running  
1               411.563588            556.086714  running  
2               467.510376            371.699350  running  
3               127.782515            358.725876  running  
4               209.194516            517.560493  running  
...               

In [11]:
import pandas as pd
import os
import numpy as np
from scipy.stats import entropy

#  путь к каталогу, содержащему файлы CSV
directory_path = r'f:\Dell\Data_Science\HW_DS_5\data\stairs'

#  пустой список, в который будут добавлены все DataFrame
all_dataframes = []

# список файлов в указанном каталоге
file_list = os.listdir(directory_path)

# чтение  каждого файла и сохранение его в DataFrame
for file_name in file_list:
    if file_name.endswith(".csv"):  
        file_path = os.path.join(directory_path, file_name)
        df = pd.read_csv(file_path)
        
        #  максимальные и минимальные значения для каждой оси движения
        max_x = df['accelerometer_X'].max()
        min_x = df['accelerometer_X'].min()
        max_y = df['accelerometer_Y'].max()
        min_y = df['accelerometer_Y'].min()
        max_z = df['accelerometer_Z'].max()
        min_z = df['accelerometer_Z'].min()
        
        # интерквартильный диапазон для столбца "accelerometer_X"
        iqr_x = df['accelerometer_X'].quantile(0.75) - df['accelerometer_X'].quantile(0.25)
        
        # Дополнительные метрики для столбца "accelerometer_Y"
        mean_y = df['accelerometer_Y'].mean()
        variance_y = df['accelerometer_Y'].var()
        std_dev_y = df['accelerometer_Y'].std()
        median_y = df['accelerometer_Y'].median()
        rms_y = np.sqrt(np.mean(df['accelerometer_Y'] ** 2))
        
        # Дополнительные метрики для столбца "accelerometer_Z"
        skewness_z = df['accelerometer_Z'].skew()
        kurtosis_z = df['accelerometer_Z'].kurt()
        iqr_z = df['accelerometer_Z'].quantile(0.75) - df['accelerometer_Z'].quantile(0.25)
        
        #  энтропию для каждой оси движения
        entropy_x = entropy(df['accelerometer_X'])
        entropy_y = entropy(df['accelerometer_Y'])
        entropy_z = entropy(df['accelerometer_Z'])
        
        # кросс-корреляцию бинарных комбинаций x, y и z
        cross_correlation_xy = np.correlate(df['accelerometer_X'], df['accelerometer_Y'], mode='same')
        cross_correlation_xz = np.correlate(df['accelerometer_X'], df['accelerometer_Z'], mode='same')
        cross_correlation_yz = np.correlate(df['accelerometer_Y'], df['accelerometer_Z'], mode='same')
        
        # все вычисленные метрики в датафрейм
        df['maximum_value_x'] = max_x
        df['minimum_value_x'] = min_x
        df['maximum_value_y'] = max_y
        df['minimum_value_y'] = min_y
        df['maximum_value_z'] = max_z
        df['minimum_value_z'] = min_z
        df['interquartile_range_x'] = iqr_x
        df['mean_y'] = mean_y
        df['variance_y'] = variance_y
        df['std_dev_y'] = std_dev_y
        df['median_y'] = median_y
        df['rms_y'] = rms_y
        df['entropy_x'] = entropy_x
        df['entropy_y'] = entropy_y
        df['entropy_z'] = entropy_z
        df['skewness_z'] = skewness_z
        df['kurtosis_z'] = kurtosis_z
        df['iqr_z'] = iqr_z
        df['cross_correlation_xy'] = cross_correlation_xy
        df['cross_correlation_xz'] = cross_correlation_xz
        df['cross_correlation_yz'] = cross_correlation_yz
        df ["id"] = 'stairs'
        all_dataframes.append(df)
        
# объединение в один  DataFrame:
df_stairs = pd.concat(all_dataframes, ignore_index=True)
df_stairs = df_stairs.iloc[:2000]
df_stairs

accelerometer_X  accelerometer_Y  accelerometer_Z  maximum_value_x  \
0            6.727707         2.973599         3.936068         8.073248   
1            7.891289         0.440533        -3.342306         8.073248   
2            6.301539        -1.154005         0.067038         8.073248   
3            4.534618        -5.755661        -1.369483         8.073248   
4            4.563349        -3.730166        -0.028730         8.073248   
...               ...              ...              ...              ...   
1995         0.052672       -17.745823        -3.203442         5.185841   
1996        -7.939172       -14.302961       -13.105860         5.185841   
1997        -2.489970        -8.829816         3.193865         5.185841   
1998         0.871489       -11.013328         0.885855         5.185841   
1999         2.686294        -8.963891        -3.883395         5.185841   

      minimum_value_x  maximum_value_y  minimum_value_y  maximum_value_z  \
0           -4.582502         2.973599       -17.300500        10.582372   
1           -4.582502         2.973599       -17.300500        10.582372   
2           -4.582502         2.973599       -17.300500        10.582372   
3           -4.582502         2.973599       -17.300500        10.582372   
4           -4.582502         2.973599       -17.300500        10.582372   
...               ...              ...              ...              ...   
1995        -7.939172         0.526724       -22.117636         4.031836   
1996        -7.939172         0.526724       -22.117636         4.031836   
1997        -7.939172         0.526724       -22.117636         4.031836   
1998        -7.939172         0.526724       -22.117636         4.031836   
1999        -7.939172         0.526724       -22.117636         4.031836   

      minimum_value_z  interquartile_range_x  ...  entropy_x  entropy_y  \
0          -14.422671               3.848680  ...       -inf       -inf   
1          -14.422671               3.848680  ...       -inf       -inf   
2          -14.422671               3.848680  ...       -inf       -inf   
3          -14.422671               3.848680  ...       -inf       -inf   
4          -14.422671               3.848680  ...       -inf       -inf   
...               ...                    ...  ...        ...        ...   
1995       -28.031313               2.694674  ...       -inf       -inf   
1996       -28.031313               2.694674  ...       -inf       -inf   
1997       -28.031313               2.694674  ...       -inf       -inf   
1998       -28.031313               2.694674  ...       -inf       -inf   
1999       -28.031313               2.694674  ...       -inf       -inf   

      entropy_z  skewness_z  kurtosis_z     iqr_z  cross_correlation_xy  \
0          -inf   -0.473734    3.758635  3.256115           -498.964946   
1          -inf   -0.473734    3.758635  3.256115           -387.021309   
2          -inf   -0.473734    3.758635  3.256115           -479.071399   
3          -inf   -0.473734    3.758635  3.256115           -681.275438   
4          -inf   -0.473734    3.758635  3.256115           -605.801677   
...         ...         ...         ...       ...                   ...   
1995       -inf   -2.822831   10.797666  4.088099           -100.696979   
1996       -inf   -2.822831   10.797666  4.088099             49.638834   
1997       -inf   -2.822831   10.797666  4.088099            -60.912264   
1998       -inf   -2.822831   10.797666  4.088099           -246.333497   
1999       -inf   -2.822831   10.797666  4.088099           -157.576796   

      cross_correlation_xz  cross_correlation_yz      id  
0               -35.765584           -117.151968  stairs  
1                82.245885           -215.320694  stairs  
2               -27.261072            -43.398059  stairs  
3               -78.240518              0.966439  stairs  
4               -27.376988            -86.017386  stairs  
...                    .

In [16]:
import pandas as pd
import os
import numpy as np
from scipy.stats import entropy

#  путь к каталогу, содержащему файлы CSV
directory_path = r'f:\Dell\Data_Science\HW_DS_5\data\walking'

#  пустой список, в который будут добавлены все DataFrame
all_dataframes = []

# список файлов в указанном каталоге
file_list = os.listdir(directory_path)

# чтение  каждого файла и сохранение его в DataFrame
for file_name in file_list:
    if file_name.endswith(".csv"):  
        file_path = os.path.join(directory_path, file_name)
        df = pd.read_csv(file_path)
        
        #  максимальные и минимальные значения для каждой оси движения
        max_x = df['accelerometer_X'].max()
        min_x = df['accelerometer_X'].min()
        max_y = df['accelerometer_Y'].max()
        min_y = df['accelerometer_Y'].min()
        max_z = df['accelerometer_Z'].max()
        min_z = df['accelerometer_Z'].min()
        
        # интерквартильный диапазон для столбца "accelerometer_X"
        iqr_x = df['accelerometer_X'].quantile(0.75) - df['accelerometer_X'].quantile(0.25)
        
        # Дополнительные метрики для столбца "accelerometer_Y"
        mean_y = df['accelerometer_Y'].mean()
        variance_y = df['accelerometer_Y'].var()
        std_dev_y = df['accelerometer_Y'].std()
        median_y = df['accelerometer_Y'].median()
        rms_y = np.sqrt(np.mean(df['accelerometer_Y'] ** 2))
        
        # Дополнительные метрики для столбца "accelerometer_Z"
        skewness_z = df['accelerometer_Z'].skew()
        kurtosis_z = df['accelerometer_Z'].kurt()
        iqr_z = df['accelerometer_Z'].quantile(0.75) - df['accelerometer_Z'].quantile(0.25)
        
        #  энтропию для каждой оси движения
        entropy_x = entropy(df['accelerometer_X'])
        entropy_y = entropy(df['accelerometer_Y'])
        entropy_z = entropy(df['accelerometer_Z'])
        
        # кросс-корреляцию бинарных комбинаций x, y и z
        cross_correlation_xy = np.correlate(df['accelerometer_X'], df['accelerometer_Y'], mode='same')
        cross_correlation_xz = np.correlate(df['accelerometer_X'], df['accelerometer_Z'], mode='same')
        cross_correlation_yz = np.correlate(df['accelerometer_Y'], df['accelerometer_Z'], mode='same')
        
        # все вычисленные метрики в датафрейм
        df['maximum_value_x'] = max_x
        df['minimum_value_x'] = min_x
        df['maximum_value_y'] = max_y
        df['minimum_value_y'] = min_y
        df['maximum_value_z'] = max_z
        df['minimum_value_z'] = min_z
        df['interquartile_range_x'] = iqr_x
        df['mean_y'] = mean_y
        df['variance_y'] = variance_y
        df['std_dev_y'] = std_dev_y
        df['median_y'] = median_y
        df['rms_y'] = rms_y
        df['entropy_x'] = entropy_x
        df['entropy_y'] = entropy_y
        df['entropy_z'] = entropy_z
        df['skewness_z'] = skewness_z
        df['kurtosis_z'] = kurtosis_z
        df['iqr_z'] = iqr_z
        df['cross_correlation_xy'] = cross_correlation_xy
        df['cross_correlation_xz'] = cross_correlation_xz
        df['cross_correlation_yz'] = cross_correlation_yz
        df ["id"] = 'walking'
        all_dataframes.append(df)
        
# объединение в один  DataFrame:
df_walking = pd.concat(all_dataframes, ignore_index=True)
df_walking = df_walking.iloc[:2000]
df_walking

accelerometer_X  accelerometer_Y  accelerometer_Z  maximum_value_x  \
0            2.322376         3.643975        11.827356        12.363658   
1            1.781286         4.668694         6.148310        12.363658   
2            7.963115        -4.113238         1.359907        12.363658   
3            1.996764        -1.398214         1.163582        12.363658   
4            5.185841       -12.143391         4.687847        12.363658   
...               ...              ...              ...              ...   
1995        -8.777143       -13.062764        -1.939303         3.289633   
1996         3.289633        11.439496        11.674128         3.289633   
1997        -1.498770       -12.215217        -0.234632         3.289633   
1998        -3.505111        -5.995081        -5.928043         3.289633   
1999        -1.168370       -11.444284         0.067038         3.289633   

      minimum_value_x  maximum_value_y  minimum_value_y  maximum_value_z  \
0           -2.389413         4.668694       -20.934900        11.827356   
1           -2.389413         4.668694       -20.934900        11.827356   
2           -2.389413         4.668694       -20.934900        11.827356   
3           -2.389413         4.668694       -20.934900        11.827356   
4           -2.389413         4.668694       -20.934900        11.827356   
...               ...              ...              ...              ...   
1995       -17.348385        11.439496       -22.869415        11.674128   
1996       -17.348385        11.439496       -22.869415        11.674128   
1997       -17.348385        11.439496       -22.869415        11.674128   
1998       -17.348385        11.439496       -22.869415        11.674128   
1999       -17.348385        11.439496       -22.869415        11.674128   

      minimum_value_z  interquartile_range_x  ...  entropy_x  entropy_y  \
0          -21.442470               4.782418  ...       -inf       -inf   
1          -21.442470               4.782418  ...       -inf       -inf   
2          -21.442470               4.782418  ...       -inf       -inf   
3          -21.442470               4.782418  ...       -inf       -inf   
4          -21.442470               4.782418  ...       -inf       -inf   
...               ...                    ...  ...        ...        ...   
1995       -19.531897               5.595249  ...       -inf       -inf   
1996       -19.531897               5.595249  ...       -inf       -inf   
1997       -19.531897               5.595249  ...       -inf       -inf   
1998       -19.531897               5.595249  ...       -inf       -inf   
1999       -19.531897               5.595249  ...       -inf       -inf   

      entropy_z  skewness_z  kurtosis_z     iqr_z  cross_correlation_xy  \
0          -inf   -1.635672    7.158918  2.642002           -913.697898   
1          -inf   -1.635672    7.158918  2.642002           -808.561686   
2          -inf   -1.635672    7.158918  2.642002           -902.103954   
3          -inf   -1.635672    7.158918  2.642002           -911.593628   
4          -inf   -1.635672    7.158918  2.642002           -925.991123   
...         ...         ...         ...       ...                   ...   
1995       -inf   -0.649061    1.530881  4.034229           1764.839099   
1996       -inf   -0.649061    1.530881  4.034229           1126.176510   
1997       -inf   -0.649061    1.530881  4.034229            977.644497   
1998       -inf   -0.649061    1.530881  4.034229           1075.875150   
1999       -inf   -0.649061    1.530881  4.034229            990.987832   

      cross_correlation_xz  cross_correlation_yz       id  
0               -69.330271            157.312562  walking  
1               -84.465003            146.641601  walking  
2               -47.911116             60.809379  walking  
3               -21.873620            100.362844  walking  
4                30.363482            145.015340  walking  
...               

In [17]:
# Объедините данные из df_idle, df_running, df_stairs и df_walking в df_general
df_general = pd.concat([df_idle, df_running, df_stairs, df_walking]).reset_index(drop=True)
df_general

accelerometer_X  accelerometer_Y  accelerometer_Z  maximum_value_x  \
0            1.000776         4.616021         8.576031         5.099650   
1            0.718261         4.209007         8.446744         5.099650   
2           -0.909797        -0.282516         9.203311         5.099650   
3            5.099650         0.148441         8.418014         5.099650   
4            1.762132        -0.162806         9.251195         5.099650   
...               ...              ...              ...              ...   
7995        -8.777143       -13.062764        -1.939303         3.289633   
7996         3.289633        11.439496        11.674128         3.289633   
7997        -1.498770       -12.215217        -0.234632         3.289633   
7998        -3.505111        -5.995081        -5.928043         3.289633   
7999        -1.168370       -11.444284         0.067038         3.289633   

      minimum_value_x  maximum_value_y  minimum_value_y  maximum_value_z  \
0           -0.909797         4.616021        -0.282516         9.806650   
1           -0.909797         4.616021        -0.282516         9.806650   
2           -0.909797         4.616021        -0.282516         9.806650   
3           -0.909797         4.616021        -0.282516         9.806650   
4           -0.909797         4.616021        -0.282516         9.806650   
...               ...              ...              ...              ...   
7995       -17.348385        11.439496       -22.869415        11.674128   
7996       -17.348385        11.439496       -22.869415        11.674128   
7997       -17.348385        11.439496       -22.869415        11.674128   
7998       -17.348385        11.439496       -22.869415        11.674128   
7999       -17.348385        11.439496       -22.869415        11.674128   

      minimum_value_z  interquartile_range_x  ...  entropy_x  entropy_y  \
0            8.418014               0.065840  ...       -inf       -inf   
1            8.418014               0.065840  ...       -inf       -inf   
2            8.418014               0.065840  ...       -inf       -inf   
3            8.418014               0.065840  ...       -inf       -inf   
4            8.418014               0.065840  ...       -inf       -inf   
...               ...                    ...  ...        ...        ...   
7995       -19.531897               5.595249  ...       -inf       -inf   
7996       -19.531897               5.595249  ...       -inf       -inf   
7997       -19.531897               5.595249  ...       -inf       -inf   
7998       -19.531897               5.595249  ...       -inf       -inf   
7999       -19.531897               5.595249  ...       -inf       -inf   

      entropy_z  skewness_z  kurtosis_z     iqr_z  cross_correlation_xy  \
0      3.400301   -2.365312    4.369874  0.034716             -0.817845   
1      3.400301   -2.365312    4.369874  0.034716             -0.679793   
2      3.400301   -2.365312    4.369874  0.034716             -0.889869   
3      3.400301   -2.365312    4.369874  0.034716             -0.774927   
4      3.400301   -2.365312    4.369874  0.034716             -0.756009   
...         ...         ...         ...       ...                   ...   
7995       -inf   -0.649061    1.530881  4.034229           1764.839099   
7996       -inf   -0.649061    1.530881  4.034229           1126.176510   
7997       -inf   -0.649061    1.530881  4.034229            977.644497   
7998       -inf   -0.649061    1.530881  4.034229           1075.875150   
7999       -inf   -0.649061    1.530881  4.034229            990.987832   

      cross_correlation_xz  cross_correlation_yz       id  
0                65.278404             69.562411     idle  
1                64.322335             68.427268     idle  
2                62.989091             67.019064     idle  
3                61.532475             65.808561     idle  
4                60.632498             64.651785     idle  
...               

In [ ]:
pip install scikit-learn

In [29]:
shape = df_general.shape
print("Форма combined_data:", shape)

Форма combined_data: (8000, 25)


In [54]:
#Разбиваем датасет на признаки (features) и целевую переменную (target variable).
X = df_general[['accelerometer_X', 'accelerometer_Y', 'accelerometer_Z']]
y = df_general['id']

In [44]:
#Разбиваем датасет на тренировочный набор и тестовый набор
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [46]:
# обучение модели SVM
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
svm_model = SVC(kernel='rbf')
svm_model.fit(X_train, y_train)

SVC()

In [ ]:
SVC()

In [41]:
# Навчання моделі Випадкового лісу
rf_model = RandomForestClassifier()
rf_model.fit(X_train, y_train)

RandomForestClassifier()

In [ ]:
RandomForestClassifier()

In [42]:
# Прогнозирование на тестовом наборе
svm_predictions = svm_model.predict(X_test)
rf_predictions = rf_model.predict(X_test)

In [56]:
from sklearn.metrics import accuracy_score, confusion_matrix

# Оценка производительности моделей
svm_accuracy = accuracy_score(y_test, svm_predictions)
rf_accuracy = accuracy_score(y_test, rf_predictions)

svm_confusion_matrix = confusion_matrix(y_test, svm_predictions)
rf_confusion_matrix = confusion_matrix(y_test, rf_predictions)

print("Точность модели SVM:", svm_accuracy)
print("Матрица ошибок модели SVM:")
print(svm_confusion_matrix)

print("Точность модели Випадкового лісу:", rf_accuracy)
print("Матрица ошибок модели Випадкового лісу:")
print(rf_confusion_matrix)

Точность модели SVM: 0.779375
Матрица ошибок модели SVM:
[[425   0   0   0]
 [  6 312  45  16]
 [  2  18 211 166]
 [  1  19  80 299]]
Точность модели Випадкового лісу: 0.991875
Матрица ошибок модели Випадкового лісу:
[[425   0   0   0]
 [  1 377   1   0]
 [  0   4 391   2]
 [  1   2   2 394]]
